version: '3.8'

services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000" 
    # When the container spins up, we pass the exact database URL through the environment variable
    environment:
      - DATABASE_URL=mysql+pymysql://root:1234#ReWq@db-mysql:3306/db
    depends_on:
      db-mysql:
        condition: service_healthy
    
  db-mysql:
    image: mysql:latest
    container_name: "test-mysql-db"
    environment:
      MYSQL_ROOT_PASSWORD: "1234#ReWq"
      MYSQL_DATABASE: "dbtest"
    ports:
      - "3307:3306" # Use 3307 for programs outside Docker, the application inside Docker uses 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234#ReWq"]
      interval: 5s
      timeout: 5s
      retries: 5
